load("//cfg:fsl.bzl", "fsl_compile")

cxx_binary(
    name = "01_Transformations",
    srcs = ["01_Transformations.cpp"],
    link_style = "static",
    deps = [
        "//:TF",
    ],
    visibility = ['//Samples:']
)

fsl_compile(
    name = "fsl",
    srcs = ["Shaders/FSL/ShaderList.fsl", "//:UI_ShaderList", "//:Font_ShaderList"],
    visibility = ['//Samples:']
)

export_file(
    name = "gpu.cfg",
    mode = "reference",
    src = "gpu.cfg",
    visibility = ['PUBLIC']
)

