load("//:rules.bzl", "fsl_build", "package_app")

cxx_binary(
    name = "01_Transformations",
    srcs = ["01_Transformations.cpp"],
    link_style = "static",
    deps = [
        "//:TF",
    ],
  visibility = ['//Samples:']
)
fsl_build(
    name = "fsl",
    srcs = ["Shaders/FSL/ShaderList.fsl", "//:UI_ShaderList", "//:Font_ShaderList"],
    visibility = ['//Samples:']
)





