
load("@tf//:defs.bzl", "tf_default_shared_deps")

cxx_library(
  name = "TF_utest",
  exported_headers = { 
    "TF_TestMain.h":"TF_TestMain.h",
    "utest.h":"utest.h" 
  },
  header_namespace = "",
  link_style = "static",
  visibility = ['PUBLIC']
)

cxx_test(
  name = 'TF_ScratchAllocatorTest',
  srcs = [
    'TF_ScratchAllocatorTest.cpp',
  ],
  link_style = "static",
  deps = [
      "@tf//:TF",
      ":TF_utest"
  ],
  visibility = ['PUBLIC']
)

cxx_test(
  name = 'TF_GPUConfigTest',
  srcs = [
    'TF_GPUConfigTest.cpp',
  ],
  link_style = "static",
  extra_shared_deps = tf_default_shared_deps(),
  deps = [
    "@tf//:TF",
    ":TF_utest"
  ],
  visibility = ['PUBLIC']
)

cxx_test(
  name = 'TF_StringTest',
  srcs = [
    'TF_StringTest.cpp',
  ],
  link_style = "static",
  deps = [
      "@tf//:TF",
      ":TF_utest"
  ],
  visibility = ['PUBLIC']
)

cxx_test(
  name = 'TF_PlyTest',
  srcs = [
    'TF_PlyTest.cpp',
  ],
  link_style = "static",
  deps = [
      "@tf//:TF",
      "@tf//:TF~Ply",
      ":TF_utest"
  ],
  visibility = ['PUBLIC']
)
