load("//:rules.bzl", "package_app")

package_app(
    name = "01_Transformation",
    resources = [ 
        "//Samples/Unit_Tests/01_Transformations:01_Transformations",
        "//Samples/Unit_Tests/01_Transformations:fsl",
        #"//:ui_fsl"
  ],
  files =  {file: file for file in glob(["TFSamples-Media/UnitTestResources/Textures/dds/circlepad.tex"])}
) 


