name: CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-3-dev libudev-dev libx11-dev libxrandr-dev 
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          rustup install nightly-2024-04-28
          cargo +nightly-2024-04-28 install --git https://github.com/facebook/buck2.git buck2
      - name: Run Test 
        run: |
          export PATH=$HOME/.cargo/bin:$PATH
          cd ${{ github.workspace }}
          buck2 test --target-platforms tf_platform//:linux_x86_64 tf//...
