name: CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-3-dev libudev-dev libx11-dev libxrandr-dev
      - uses: dtolnay/install-buck2@latest
      - name: Run Test 
        run: |
          export PATH=$HOME/.cargo/bin:$PATH
          cd ${{ github.workspace }}
          buck2 test --target-platforms tf_platform//:linux_x86_64 tf//...
